[package]
name = "s4ddle"
version = "0.1.0"
edition = "2021"
description = "Solvers for Sparse Symmetric Systems of Linear Equations"
readme = "README.md"
repository = "https://github.com/jevgarrido/s4ddle.git"
license = "MIT OR Apache-2.0"
keywords = ["no_std"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["std"]
std = []

