name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Dropbox import
      uses: tlambert03/dropbox-download-action@v1
      with:
        dropbox-refresh-token: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
        dropbox-app-key: ${{ secrets.DROPBOX_APP_KEY }}
        dropbox-app-secret: ${{ secrets.DROPBOX_APP_SECRET }}
        source-path: "./test-data/symmetric-matrices"
        dest-path: "./data"
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
