name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Dropbox import
      uses: gbrls/action-dropbox-download@main
      with:
          dropbox-refresh-token: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          source-path: '/test-data/symmetric-matrices'
          destination-path: '/data'
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
