name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Dropbox import
      uses: lgxm3z/gh-actions-dropbox/files/download_zip@2
      with:
        DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
        DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
        DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
        SOURCE_PATH: /test-data/symmetric-matrices
        DEST_PATH: /data/matrices.zip
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose
